### ISSUE TITLE
bower_boost.js的无法编译bower.json中main: [ 'fonts/*' ] 这种目录

### ISSUE THREAD

**Issue by ThienZhao** [hefangshi/pure-angular-demo#1]
使用bower_boost.js编译过程中，发现无法加载最新的font-awesome组件，原因是font-awesome中的bower.json中的main: [ 'fonts/*' ], 带有星号的bower_boost.js无法加载

**Comment by hefangshi** [comment]
你确定获取的是最新的代码么，这个问题很久以前就修复了呀，是支持 \* 号的

**Comment by ThienZhao** [comment]
确实是使用最新的版本。 我在用bower 下载font-awesome这个组件的时候，发现其bower.json中配置的main如下：  "main": [
    "./css/font-awesome.css",
    "./fonts/*"
  ],
导致 /fonts/目录下的文件不能加载！！
你们可以测试下

**Comment by hefangshi** [comment]
恩，发现问题了，是 Windows 下的 `path.sep` 与 UNIX 下不同导致的，已经修复了，可以重新获取一下最新代码。
