### ISSUE TITLE
 关于报$digest already in progress的错误

### ISSUE THREAD

**Issue by liguanrui** [hefangshi/pure-angular-demo#2]
问题来源并不在这个 `fis-pure-angular-demo`，而是在 `fis3-angular-demo` 的例子，地址如下

> https://github.com/zhangtao07/fis3-angular-demo

主要描述：
- 由于fis3的例子中modules/pages/tables/tables.js用了require.async异步加载controller
- 路由一进来如果就是http://127.0.0.1:8080/#/tables ，需要$scope.$apply()一下;

问题来了：

> console后台会默默地报出 $digest already in progress 的错误！

解决：
修改 /modules/pages/tables/tableCtrl.async.js 文件内容

```
var scope= ['$scope', function($scope) {
    $scope.test = '异步加载测试';
    if(!$scope.$$phase) {
        $scope.$apply();
    }
}];

return scope;
```

**Comment by hefangshi** [comment]
可以提个PR么？ @zhangtao07 看看~

**Comment by liguanrui** [comment]
已经提给 @zhangtao07 了

**Comment by hefangshi** [comment]
@liguanrui 好的，感谢
